#!/bin/sh

# creates compiled directory 
if [ ! -d "compiled" ]; then
    mkdir compiled
fi

# either this fails spectacularly or it works like a charm, 
for file_name in c/*.c; do
    output_file="compiled/$(basename ${file_name%.c})"
    if $(gcc -o $output_file $file_name -Wall -Wpedantic -Wextra); then 
        echo "${file_name#c/} compiled into $output_file succesfully"
    else
        echo "$file_name failed to compile"
    fi
done

exit 0
